steps:
  - name: gcr.io/cloud-builders/git
    args:
      - '-c'
      - |
        echo "$$SSHKEY" > /root/.ssh/id_rsa
        chmod 400 /root/.ssh/id_rsa
        ssh-keyscan git.epam.com > /root/.ssh/known_hosts
    entrypoint: bash
    secretEnv:
      - SSHKEY
    volumes:
      - name: ssh
        path: /root/.ssh
  - name: gcr.io/cloud-builders/git
    args:
      - clone
      - 'git@git.epam.com:epm-gcp/ml-specialization-demo2.git'
    entrypoint: git
    volumes:
      - name: ssh
        path: /root/.ssh
  - name: 'gcr.io/cloud-builders/docker'
    args: [
        'build',
        '--tag',
        'gcr.io/${PROJECT_ID}/tfx-pipeline-ml-demo2-black-friday-vertex',
        '.'
    ]
  - name: 'python:3.7-slim'
    args:
      - '-c'
      - |
        cd ml-specialization-demo2/tfx-pipeline
        pip install -r requirements.txt
        python vertex_compile.py
        python vertex_run.py'
    entrypoint: /bin/sh
    timeout: 3600s
images: ['gcr.io/${PROJECT_ID}/tfx-pipeline-ml-demo2-black-friday-vertex']
timeout: 3600s
availableSecrets:
  secretManager:
    - versionName: projects/877218744686/secrets/ssh-gitlab-secret/versions/1
      env: SSHKEY
